-- Generated by scripts/audit_relations.py
-- REVIEW BEFORE RUNNING. This deletes flagged relations.
-- 0 relation rows targeted.
-- Known HCM case included: no

-- No bad relations detected. Nothing to delete.
